# Generated by Django 3.1.7 on 2021-07-18 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
