# Generated by Django 3.1.7 on 2021-07-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0003_project_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='score',
        ),
    ]
