# Generated by Django 3.1.7 on 2021-07-19 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0005_rating_content_object_rating_design_object_rating_usability_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_content_object',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating_design_object',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rating_usability_object',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
