# Generated by Django 3.1.7 on 2021-07-19 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0006_auto_20210719_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, 'cannot be more than 10'), django.core.validators.MinValueValidator(1, 'cannot be less than 1')])),
                ('usability', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, 'cannot be more than 10'), django.core.validators.MinValueValidator(1, 'cannot be less than 1')])),
                ('content', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10, 'cannot be more than 10'), django.core.validators.MinValueValidator(1, 'cannot be less than 1')])),
                ('score_description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratingapp.project')),
                ('user_profile', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ratingapp.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='rating_design_object',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rating_design_object',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating_usability_object',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rating_usability_object',
            name='user',
        ),
        migrations.DeleteModel(
            name='rating_content_object',
        ),
        migrations.DeleteModel(
            name='rating_design_object',
        ),
        migrations.DeleteModel(
            name='rating_usability_object',
        ),
    ]
